### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by sakonachhoeurng** [paulgibbs/behat-wordpress-extension#105]
I think it already has an issue similarly with https://github.com/paulgibbs/behat-wordpress-extension/issues/47
But I do has another different scenario as show below.
`behat.yml`
```
PaulGibbs\WordpressBehatExtension:
      path: /home/sakona/dev/docker-projects/wordpress/local.tornio.wehost.asia/wp
      users:
        admin:
          username: essentials
          password: webessentials
```
I do not know what is different with `path /wp` because my website create another them outside `/wp` folder
My error on scenario 
```
Scenario: Login to backend         # features/homepage.feature:12
    Given I am on "wp/wp-admin"      # Behat\MinkExtension\Context\MinkContext::visit()
    Given I am logged in as an admin # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmLoggedInAs()
      Fatal error: Call to a member function focus() on null (Behat\Testwork\Call\Exception\FatalThrowableError)

--- Failed scenarios:
```
Please help for this issue, I do not know how to solve.
