### ISSUE TITLE
Fatal error: Call to a member function focus() on null (Behat\Testwork\Call\Exception\FatalThrowableError)

### ISSUE THREAD

**Issue by dealancer** [paulgibbs/behat-wordpress-extension#182]
When I run authenticate.feature with `@javascript` I get following error:

```
    Given I am logged in as an admin             # PaulGibbs\WordpressBehatExtension\Context\UserContext::iAmLoggedInAs()
      Fatal error: Call to a member function focus() on null (Behat\Testwork\Call\Exception\FatalThrowableError)

```

## Expected behaviour
Tests are passing.

## Current behaviour
Error is shown.

## Possible solution
I think it has something to do with a following code in `UserAwareContextTrait.php`:

```
        $node = $page->findField('user_login');
        try {
            $node->focus();
        } catch (UnsupportedDriverActionException $e) {
            // This will fail for GoutteDriver but neither is it necessary.
        }
```

`$node` is `null`. It looks like `$page` does not contain HTML code.

## Steps to reproduce (for bugs)
1. Add following configuration to `behat.yml`:

```
docker:
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
```

2. run `vendor/bin/behat -p docker` inside a docker container

## Context
Can not run tests with JavaScript enabled.

## Your environment
* Docksal, see https://docs.docksal.io/en/v1.6.1/tools/behat/

**Comment by paulgibbs** [comment]
Hi @dealancer 

I'll try to look in the next few days.
Which browser are you using?
Have you customised your site's wp-login.php template?

**Comment by dealancer** [comment]
@paulgibbs I think it is chrome (issue happens when I run this outside docker too). I have not customized `wp-login.php` it is just a fresh WP install.

The thing is that it works ok when @javascript is omitted. When it is present it fails.

**Comment by dealancer** [comment]
I think i narrowed down the problem. Since I run this in container there is no real browser used and that could be a problem. When I make a change:

```
javascript_session: goutte
```

I see error `The javascript session must be one of the enabled javascript sessions (["selenium2"]), but got goutte`.

So basically my question is how can I run javascript in the headless mode? Should i install phantomjs?

**Comment by dealancer** [comment]
hm.... i set up headless chrome browser in the independent container, but I am still having this issue.

Here is my configuration:

```
default:
  suites:
    default:
      contexts:
        # Keep WordpressContext first!
        - PaulGibbs\WordpressBehatExtension\Context\WordpressContext
        - FeatureContext
        - Behat\MinkExtension\Context\MinkContext
        - PaulGibbs\WordpressBehatExtension\Context\ContentContext
        - PaulGibbs\WordpressBehatExtension\Context\DashboardContext
        - PaulGibbs\WordpressBehatExtension\Context\SiteContext
        - PaulGibbs\WordpressBehatExtension\Context\UserContext
        - PaulGibbs\WordpressBehatExtension\Context\EditPostContext
        - PaulGibbs\WordpressBehatExtension\Context\WidgetContext
        - PaulGibbs\WordpressBehatExtension\Context\ToolbarContext

  extensions:
    Behat\MinkExtension:
      base_url: http://guwordpress.docksal
      default_session: goutte
      javascript_session: selenium2
      selenium2:
        browser: chrome
        wd_host: http://browser:4444/wd/hub
        capabilities:
          browser: chrome
          version: "*"
          chrome:
            switches:
              - "--headless"
              - "--disable-gpu"
      goutte:
        guzzle_parameters:
          verify: false  # Allow self-signed SSL certificates


    PaulGibbs\WordpressBehatExtension:
      default_driver: wpcli
      path: ../../docroot
      users:
        admin:
          username: guadmin
          password: admin

docker:
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
```
