### ISSUE TITLE
 WP-CLI driver failure in method bootstrap()

### ISSUE THREAD

**Issue by bartonhammond** [paulgibbs/behat-wordpress-extension#190]
Trying to run Wordhat following instructions and get following error:
```
~/projects/twlw/wp-content/themes/jumpoff (master)$ vendor/bin/behat 
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
In WpcliDriver.php line 140:
  WP-CLI driver failure in method bootstrap():                                             
  Tried to run: wp --path='/' --url='https://wwww.twlw.com' --no-color core is-installed   
```
                                                                                           
## Expected behaviour
Expected to run the Features as provided by Wordhat

## Current behaviour
I get the error above

## Possible solution
No idea

## Steps to reproduce (for bugs)
Follow the directions provided.
I am running from `/wp-content/themes/jumpoff`
the following is my `behat.yml`
```
default:
  suites:
    default:
      contexts:
        # Keep WordpressContext first!
        - PaulGibbs\WordpressBehatExtension\Context\WordpressContext
        - FeatureContext
        - Behat\MinkExtension\Context\MinkContext
        - PaulGibbs\WordpressBehatExtension\Context\ContentContext
        - PaulGibbs\WordpressBehatExtension\Context\DashboardContext
        - PaulGibbs\WordpressBehatExtension\Context\SiteContext
        - PaulGibbs\WordpressBehatExtension\Context\UserContext
        - PaulGibbs\WordpressBehatExtension\Context\EditPostContext
        - PaulGibbs\WordpressBehatExtension\Context\WidgetContext
        - PaulGibbs\WordpressBehatExtension\Context\ToolbarContext

  extensions:
    Behat\MinkExtension:
      base_url: https://wwww.twlw.com
      browser_name: chrome
      default_session: default
      javascript_session: selenium2
      sessions:
        default:
          goutte:
            guzzle_parameters:
              verify: false  # Allow self-signed SSL certificates
        selenium2:
          selenium2: ~

    PaulGibbs\WordpressBehatExtension:
      default_driver: wpcli
      path: /../../../
      users:
        admin:
          username: admin
          password: admin
```

## Context
Just trying to prove that Wordhat works 

## Your environment

* Version used: 
```
{
    "name": "wisnet/twlw",
    "description": "Thoughtfulnes website",
    "type": "project",
    "require": {
    },
    "require-dev": {
        "paulgibbs/behat-wordpress-extension": "^1.0",
        "behat/mink-goutte-driver": "^1.2",
        "behat/mink-selenium2-driver": "^1.3",
        "psy/psysh": "^0.8.17"	
    }
}
```
* Php 7.2.1
* Using MAMP with certs
* Mac 10.11.13

**Comment by paulgibbs** [comment]
Hi @bartonhammond, thanks for trying WordHat.

I can't spend much time today supporting this, but I'll try to help resolve your problems this week.
Are you intending to run this on your server for your website (with WP-CLI), or do you intend to connect to your website remotely over WP-CLI?

**Comment by bartonhammond** [comment]
Hi @paulgibbs - thanks for responding.

I am running the test locally on my Mac 10.13.3 (I provided wrong version earlier)

when I was running the tests yesterday, I put paused the test w/ Pyshell - the chrome browser would display w/ `; data()` but it wouldn't go to the home page.  If I entered in the URL manually it would look fine.

But now I can't even get the browser to come up.  I am going redo the steps now.

**Comment by bartonhammond** [comment]
I went back through everything and re-copied the `behat.yml`.  I tried this: `vendor/bin/behat -dl` and now see this:

```~/projects/twlw/wp-content/themes/jumpoff (master)$ vendor/bin/behat -dl
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.

In WpcliDriver.php line 140:

  WP-CLI driver failure in method bootstrap():                                             
  .                                                                                        
  Tried to run: wp --path='/' --url='https://wwww.twlw.com' --no-color core is-installed   
  (1)                                                                                      
```

My `behat.yml`.  The `path` is because I'm in the `jumpoff` directory.

```
default:
  suites:
    default:
      contexts:
        # Keep WordpressContext first!
        - PaulGibbs\WordpressBehatExtension\Context\WordpressContext
        - FeatureContext
        - Behat\MinkExtension\Context\MinkContext
        - PaulGibbs\WordpressBehatExtension\Context\ContentContext
        - PaulGibbs\WordpressBehatExtension\Context\DashboardContext
        - PaulGibbs\WordpressBehatExtension\Context\SiteContext
        - PaulGibbs\WordpressBehatExtension\Context\UserContext
        - PaulGibbs\WordpressBehatExtension\Context\EditPostContext
        - PaulGibbs\WordpressBehatExtension\Context\WidgetContext
        - PaulGibbs\WordpressBehatExtension\Context\ToolbarContext

  extensions:
    Behat\MinkExtension:
      base_url: https://wwww.twlw.com      
      browser_name: chrome
      default_session: default
      javascript_session: selenium2
      sessions:
        default:
          goutte:
            guzzle_parameters:
              verify: false  # Allow self-signed SSL certificates
        selenium2:
          selenium2: ~

    PaulGibbs\WordpressBehatExtension:
      default_driver: wpcli
      path: /../../../
      users:
        admin:
          username: admin
          password: admin
  ```
