### ISSUE TITLE
Add sample for PhantomJs

### ISSUE THREAD

**Issue by clemens-tolboom** [paulgibbs/behat-wordpress-extension#200]
I like to use PhantomJs instead of Selenium. Comparing the config from https://github.com/paulgibbs/behat-wordpress-extension/blob/master/behat.yml.dist with those for PhantomJs on https://gist.github.com/callado4/5068836 I'm not sure how the difference have to be read/fixed.

```yaml
  extensions:
    Behat\MinkExtension:
      base_url: http://your-wordpress-site.example.com
      browser_name: chrome
      default_session: default
      javascript_session: selenium2
      sessions:
        default:
          goutte:
            guzzle_parameters:
              verify: false  # Allow self-signed SSL certificates
        selenium2:
          selenium2: ~
```

versus

```yaml
    extensions:
        Behat\MinkExtension:
            base_url: http://demo.wp
            goutte: ~
            selenium2:
                wd_host: "http://localhost:8643/wd/hub"
```

## Expected behaviour

My PhantomJs config seems to work `behat -p phantomjs` but why has the advised version using selenium so much extra settings?

Maybe we could document each setting or add good pointers?

## Current behaviour

Me puzzled

## Possible solution

Add example for using PhantomJs commented out.

## Context

IMHO the setup for PhantomJs is easier so maybe help people to use WordHat more easily.
