### ISSUE TITLE
User roles with hyphens in their name are not supported

### ISSUE THREAD

**Issue by ollietreend** [paulgibbs/behat-wordpress-extension#210]
## Expected behaviour
I have a custom user role called `web-administrator`.

I should be able to configure this role in `behat.yml` with a username & password.

## Current behaviour
Behat ouputs the error message:

```
In ArrayNode.php line 311:

  Unrecognized option "web_administrator" under "testwork.wordpress.users"

```

Notice the hyphen in `web-administrator` has become an underscore, and therefore this role does not exist in my WordPress site.

## Possible solution
Hyphens are not allowed in YAML keys, but they are allowed in WordPress role names.

Allow underscores to match against hyphens in role names.

e.g. `web_administrator` in `behat.yml` would first attempt to match against a `web_administrator` role in WordPress, but fall back to `web-administrator` if the former doesn't exist.

## Steps to reproduce (for bugs)

1. Create a custom user role in WordPress which contains a hypen in its name.

    ```
    wp role create web-administrator "Web Administrator" --clone=editor
    ```
2. Add configuration for this role into `behat.yml`

    ```
    default:
      extensions:
        PaulGibbs\WordpressBehatExtension:
          users:
            admin:
              username: john-smith
              password: password
            web-administrator:
              username: joe-bloggs
              password: password
    ```
3. Execute any feature – Behat will fail to initialise.
