### ISSUE TITLE
Database dump is not deleted after test is finish

### ISSUE THREAD

**Issue by killua99** [paulgibbs/behat-wordpress-extension#227]
I'm finding myself delete dump databases after each test run, I thought it would be deleted after each test or having a flag to confirm I want to delete a dump.

The case is, now it generate a dump file each test I run, sometimes you have to run several tests to achieve a feature and more when it has several scenarios.

Would be a good idea, to think about this two options.

One define a database to be the restore point, so we have an option like: 

```yaml
database:
  restore_after_test: true
  backup_path: /path/to/the/dump.sql
```

That if you give a SQL file will be use for all restores points. But if we have this setting.

```yaml
database:
  restore_after_test: true
  backup_path: /path/to/store/tmp/database
```
Is a folder where the test will dump the database and after the test is finish, it will clear the database.

The difference are on, the first one when we give the database file it wont delete it, the second one when is a path that will assume is a tmp dump and it will be deleted after that.

Sorry if this issue is wrong target or so I was seeking for help but it could also be a feature request?

Thanks for this extension btw!
